export const ADDPROJECT_REQUEST = "ADDPROJECT_REQUEST";
export const ADDPROJECT_SUCCESS = "ADDPROJECT_SUCCESS";
export const ADDPROJECT_FAILURE = "ADDPROJECT_FAILURE";

export const GETPROJECT_REQUEST = "GETPROJECT_REQUEST";
export const GETPROJECT_SUCCESS = "GETPROJECT_SUCCESS";
export const GETPROJECT_FAILURE = "GETPROJECT_FAILURE";

export const UPDATEPROJECT_REQUEST = "UPDATEPROJECT_REQUEST";
export const UPDATEPROJECT_SUCCESS = "UPDATEPROJECT_SUCCESS";
export const UPDATEPROJECT_FAILURE = "UPDATEPROJECT_FAILURE";

export const ALLUSERS_REQUEST = "ALLUSERS_REQUEST";
export const ALLUSERS_SUCCESS = "ALLUSERS_SUCCESS";
export const ALLUSERS_FAILURE = "ALLUSERS_FAILURE";