export const ADDTASK_REQUEST = "ADDTASK_REQUEST";
export const ADDTASK_SUCCESS = "ADDTASK_SUCCESS";
export const ADDTASK_FAILURE = "ADDTASK_FAILURE";

export const GETTASKS_REQUEST = "GETTASKS_REQUEST";
export const GETTASKS_SUCCESS = "GETTASKS_SUCCESS";
export const GETTASKS_FAILURE = "GETTASKS_FAILURE";

export const UPDATETASK_REQUEST = "UPDATETASK_REQUEST";
export const UPDATETASK_SUCCESS = "UPDATETASK_SUCCESS";
export const UPDATETASK_FAILURE = "UPDATETASK_FAILURE";

export const DELETETASK_REQUEST = "DELETETASK_REQUEST";
export const DELETETASK_SUCCESS = "DELETETASK_SUCCESS";
export const DELETETASK_FAILURE = "DELETETASK_FAILURE";


